In [2]:
from sklearn import svm
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.datasets import make_blobs
%matplotlib inline


X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC()
clf.fit(X, y)
prediction = clf.predict([[2., 2.]])

In [39]:
[*prediction]

[1]

In [40]:
clf.support_vectors_

array([[0., 0.],
       [1., 1.]])

In [41]:
clf.n_support_

array([1, 1])

In [42]:
clf.support_

array([0, 1])

In [73]:
###  Multi-class classification   on  ovo style

X1 = [[0], [1], [2], [3]]
Y1 = [0, 1, 2, 3]
                    
clf1 = svm.SVC(decision_function_shape='ovo')
clf1.fit(X1, Y1)
dec = clf1.decision_function([[1], [2]])
clf1.dual_coef_

array([[ 1., -1., -1., -1.],
       [ 1.,  1., -1., -1.],
       [ 1.,  1.,  1., -1.]])

In [52]:
dec.shape[1]

6

In [70]:
clf1.decision_function_shape='ovr'
dec1 = clf1.decision_function([[1], [2]])
dec1.shape[1]

4

In [69]:
###  LinearSVC 
lin_clf = svm.LinearSVC()
lin_clf.fit(X1, Y1)
# np.array([1]).reshape(-1, 1) -->  [[1]]
lin_dec = lin_clf.decision_function([[1]])
lin_clf.coef_

array([[-0.90908001],
       [-0.20513331],
       [ 0.10257784],
       [ 0.41022991]])

In [1]:
### Searching the current dir
import os
cwd  = os.getcwd()
cwd

'C:\\Program Files\\CChat\\app-2.6.2-Release9744139\\Hollis\\sklearn\\SVM'

In [8]:
###   separating hyperplane for unbalanced classes

n_samples_1 = 1000
n_samples_2 = 100
centers = [[0.0, 0.0], [2.0, 2.0]]
clusters_std = [1.5, 0.5]
X, y = make_blobs(
    n_samples=[n_samples_1, n_samples_2],
    centers=centers,
    cluster_std=clusters_std,
    random_state=0,
    shuffle=False,
)
X

array([[ 2.64607852,  0.60023581],
       [ 1.46810698,  3.3613398 ],
       [ 2.80133699, -1.46591682],
       ...,
       [ 1.68550965,  2.53503626],
       [ 1.68945865,  2.86728609],
       [ 1.45085528,  2.28630668]])

In [39]:
from sklearn import datasets
iris = datasets.load_iris()
iris.data.shape

(150, 4)

In [29]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [49]:
digits = datasets.load_digits()
digits.keys()
digits.images.shape   # (1797, 8, 8)

(1797, 8, 8)

In [60]:
data = digits.images.reshape((digits.images.shape[0], -1))
data.shape

(1797, 64)